@startuml

class Car {
    id:String,
    model:String,
    brand:String
}


class CarRepository {
    + getFromDb(id:String):Car,
    + getAllFromDB():Car[]
}

class CarManager {
    + getBestCar():Car,
    + getCarsNames():String
}

CarRepository -right-> Car

CarManager -down-> CarRepository

@enduml